/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the LoginMetadataOidcProvidersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginMetadataOidcProvidersInner{}

// LoginMetadataOidcProvidersInner struct for LoginMetadataOidcProvidersInner
type LoginMetadataOidcProvidersInner struct {
	// ID of the provider, used in the login URL
	Id *string `json:"id,omitempty"`
	// Text to show on the login button
	Name *string `json:"name,omitempty"`
}

// NewLoginMetadataOidcProvidersInner instantiates a new LoginMetadataOidcProvidersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginMetadataOidcProvidersInner() *LoginMetadataOidcProvidersInner {
	this := LoginMetadataOidcProvidersInner{}
	return &this
}

// NewLoginMetadataOidcProvidersInnerWithDefaults instantiates a new LoginMetadataOidcProvidersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginMetadataOidcProvidersInnerWithDefaults() *LoginMetadataOidcProvidersInner {
	this := LoginMetadataOidcProvidersInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LoginMetadataOidcProvidersInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginMetadataOidcProvidersInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LoginMetadataOidcProvidersInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LoginMetadataOidcProvidersInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LoginMetadataOidcProvidersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginMetadataOidcProvidersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LoginMetadataOidcProvidersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LoginMetadataOidcProvidersInner) SetName(v string) {
	o.Name = &v
}

func (o LoginMetadataOidcProvidersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginMetadataOidcProvidersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableLoginMetadataOidcProvidersInner struct {
	value *LoginMetadataOidcProvidersInner
	isSet bool
}

func (v NullableLoginMetadataOidcProvidersInner) Get() *LoginMetadataOidcProvidersInner {
	return v.value
}

func (v *NullableLoginMetadataOidcProvidersInner) Set(val *LoginMetadataOidcProvidersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginMetadataOidcProvidersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginMetadataOidcProvidersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginMetadataOidcProvidersInner(val *LoginMetadataOidcProvidersInner) *NullableLoginMetadataOidcProvidersInner {
	return &NullableLoginMetadataOidcProvidersInner{value: val, isSet: true}
}

func (v NullableLoginMetadataOidcProvidersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginMetadataOidcProvidersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


