/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the ProjectBackupInventoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectBackupInventoriesInner{}

// ProjectBackupInventoriesInner struct for ProjectBackupInventoriesInner
type ProjectBackupInventoriesInner struct {
	Name *string `json:"name,omitempty"`
	Inventory *string `json:"inventory,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewProjectBackupInventoriesInner instantiates a new ProjectBackupInventoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectBackupInventoriesInner() *ProjectBackupInventoriesInner {
	this := ProjectBackupInventoriesInner{}
	return &this
}

// NewProjectBackupInventoriesInnerWithDefaults instantiates a new ProjectBackupInventoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectBackupInventoriesInnerWithDefaults() *ProjectBackupInventoriesInner {
	this := ProjectBackupInventoriesInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectBackupInventoriesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectBackupInventoriesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectBackupInventoriesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectBackupInventoriesInner) SetName(v string) {
	o.Name = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *ProjectBackupInventoriesInner) GetInventory() string {
	if o == nil || IsNil(o.Inventory) {
		var ret string
		return ret
	}
	return *o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectBackupInventoriesInner) GetInventoryOk() (*string, bool) {
	if o == nil || IsNil(o.Inventory) {
		return nil, false
	}
	return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *ProjectBackupInventoriesInner) HasInventory() bool {
	if o != nil && !IsNil(o.Inventory) {
		return true
	}

	return false
}

// SetInventory gets a reference to the given string and assigns it to the Inventory field.
func (o *ProjectBackupInventoriesInner) SetInventory(v string) {
	o.Inventory = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ProjectBackupInventoriesInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectBackupInventoriesInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ProjectBackupInventoriesInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ProjectBackupInventoriesInner) SetType(v string) {
	o.Type = &v
}

func (o ProjectBackupInventoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectBackupInventoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Inventory) {
		toSerialize["inventory"] = o.Inventory
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableProjectBackupInventoriesInner struct {
	value *ProjectBackupInventoriesInner
	isSet bool
}

func (v NullableProjectBackupInventoriesInner) Get() *ProjectBackupInventoriesInner {
	return v.value
}

func (v *NullableProjectBackupInventoriesInner) Set(val *ProjectBackupInventoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectBackupInventoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectBackupInventoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectBackupInventoriesInner(val *ProjectBackupInventoriesInner) *NullableProjectBackupInventoriesInner {
	return &NullableProjectBackupInventoriesInner{value: val, isSet: true}
}

func (v NullableProjectBackupInventoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectBackupInventoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


