/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the Runner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Runner{}

// Runner struct for Runner
type Runner struct {
	Token *string `json:"token,omitempty"`
}

// NewRunner instantiates a new Runner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunner() *Runner {
	this := Runner{}
	return &this
}

// NewRunnerWithDefaults instantiates a new Runner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunnerWithDefaults() *Runner {
	this := Runner{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *Runner) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Runner) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *Runner) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *Runner) SetToken(v string) {
	o.Token = &v
}

func (o Runner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Runner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableRunner struct {
	value *Runner
	isSet bool
}

func (v NullableRunner) Get() *Runner {
	return v.value
}

func (v *NullableRunner) Set(val *Runner) {
	v.value = val
	v.isSet = true
}

func (v NullableRunner) IsSet() bool {
	return v.isSet
}

func (v *NullableRunner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunner(val *Runner) *NullableRunner {
	return &NullableRunner{value: val, isSet: true}
}

func (v NullableRunner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


