/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the IntegrationMatcher type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationMatcher{}

// IntegrationMatcher struct for IntegrationMatcher
type IntegrationMatcher struct {
	Id *int32 `json:"id,omitempty"`
	IntegrationId *int32 `json:"integration_id,omitempty"`
	Name *string `json:"name,omitempty"`
	MatchType *string `json:"match_type,omitempty"`
	Method *string `json:"method,omitempty"`
	BodyDataType *string `json:"body_data_type,omitempty"`
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewIntegrationMatcher instantiates a new IntegrationMatcher object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationMatcher() *IntegrationMatcher {
	this := IntegrationMatcher{}
	return &this
}

// NewIntegrationMatcherWithDefaults instantiates a new IntegrationMatcher object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationMatcherWithDefaults() *IntegrationMatcher {
	this := IntegrationMatcher{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IntegrationMatcher) SetId(v int32) {
	o.Id = &v
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetIntegrationId() int32 {
	if o == nil || IsNil(o.IntegrationId) {
		var ret int32
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetIntegrationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.IntegrationId) {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasIntegrationId() bool {
	if o != nil && !IsNil(o.IntegrationId) {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given int32 and assigns it to the IntegrationId field.
func (o *IntegrationMatcher) SetIntegrationId(v int32) {
	o.IntegrationId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IntegrationMatcher) SetName(v string) {
	o.Name = &v
}

// GetMatchType returns the MatchType field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetMatchType() string {
	if o == nil || IsNil(o.MatchType) {
		var ret string
		return ret
	}
	return *o.MatchType
}

// GetMatchTypeOk returns a tuple with the MatchType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetMatchTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MatchType) {
		return nil, false
	}
	return o.MatchType, true
}

// HasMatchType returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasMatchType() bool {
	if o != nil && !IsNil(o.MatchType) {
		return true
	}

	return false
}

// SetMatchType gets a reference to the given string and assigns it to the MatchType field.
func (o *IntegrationMatcher) SetMatchType(v string) {
	o.MatchType = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *IntegrationMatcher) SetMethod(v string) {
	o.Method = &v
}

// GetBodyDataType returns the BodyDataType field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetBodyDataType() string {
	if o == nil || IsNil(o.BodyDataType) {
		var ret string
		return ret
	}
	return *o.BodyDataType
}

// GetBodyDataTypeOk returns a tuple with the BodyDataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetBodyDataTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BodyDataType) {
		return nil, false
	}
	return o.BodyDataType, true
}

// HasBodyDataType returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasBodyDataType() bool {
	if o != nil && !IsNil(o.BodyDataType) {
		return true
	}

	return false
}

// SetBodyDataType gets a reference to the given string and assigns it to the BodyDataType field.
func (o *IntegrationMatcher) SetBodyDataType(v string) {
	o.BodyDataType = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *IntegrationMatcher) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *IntegrationMatcher) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationMatcher) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *IntegrationMatcher) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *IntegrationMatcher) SetValue(v string) {
	o.Value = &v
}

func (o IntegrationMatcher) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationMatcher) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IntegrationId) {
		toSerialize["integration_id"] = o.IntegrationId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.MatchType) {
		toSerialize["match_type"] = o.MatchType
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.BodyDataType) {
		toSerialize["body_data_type"] = o.BodyDataType
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableIntegrationMatcher struct {
	value *IntegrationMatcher
	isSet bool
}

func (v NullableIntegrationMatcher) Get() *IntegrationMatcher {
	return v.value
}

func (v *NullableIntegrationMatcher) Set(val *IntegrationMatcher) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationMatcher) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationMatcher) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationMatcher(val *IntegrationMatcher) *NullableIntegrationMatcher {
	return &NullableIntegrationMatcher{value: val, isSet: true}
}

func (v NullableIntegrationMatcher) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationMatcher) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


