/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the ProjectBackupKeysInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectBackupKeysInner{}

// ProjectBackupKeysInner struct for ProjectBackupKeysInner
type ProjectBackupKeysInner struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewProjectBackupKeysInner instantiates a new ProjectBackupKeysInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectBackupKeysInner() *ProjectBackupKeysInner {
	this := ProjectBackupKeysInner{}
	return &this
}

// NewProjectBackupKeysInnerWithDefaults instantiates a new ProjectBackupKeysInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectBackupKeysInnerWithDefaults() *ProjectBackupKeysInner {
	this := ProjectBackupKeysInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectBackupKeysInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectBackupKeysInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectBackupKeysInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectBackupKeysInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ProjectBackupKeysInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectBackupKeysInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ProjectBackupKeysInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ProjectBackupKeysInner) SetType(v string) {
	o.Type = &v
}

func (o ProjectBackupKeysInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectBackupKeysInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableProjectBackupKeysInner struct {
	value *ProjectBackupKeysInner
	isSet bool
}

func (v NullableProjectBackupKeysInner) Get() *ProjectBackupKeysInner {
	return v.value
}

func (v *NullableProjectBackupKeysInner) Set(val *ProjectBackupKeysInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectBackupKeysInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectBackupKeysInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectBackupKeysInner(val *ProjectBackupKeysInner) *NullableProjectBackupKeysInner {
	return &NullableProjectBackupKeysInner{value: val, isSet: true}
}

func (v NullableProjectBackupKeysInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectBackupKeysInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


