/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the ProjectProjectIdUsersUserIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectProjectIdUsersUserIdPutRequest{}

// ProjectProjectIdUsersUserIdPutRequest struct for ProjectProjectIdUsersUserIdPutRequest
type ProjectProjectIdUsersUserIdPutRequest struct {
	Role *string `json:"role,omitempty"`
}

// NewProjectProjectIdUsersUserIdPutRequest instantiates a new ProjectProjectIdUsersUserIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectProjectIdUsersUserIdPutRequest() *ProjectProjectIdUsersUserIdPutRequest {
	this := ProjectProjectIdUsersUserIdPutRequest{}
	return &this
}

// NewProjectProjectIdUsersUserIdPutRequestWithDefaults instantiates a new ProjectProjectIdUsersUserIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectProjectIdUsersUserIdPutRequestWithDefaults() *ProjectProjectIdUsersUserIdPutRequest {
	this := ProjectProjectIdUsersUserIdPutRequest{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ProjectProjectIdUsersUserIdPutRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProjectIdUsersUserIdPutRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ProjectProjectIdUsersUserIdPutRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ProjectProjectIdUsersUserIdPutRequest) SetRole(v string) {
	o.Role = &v
}

func (o ProjectProjectIdUsersUserIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectProjectIdUsersUserIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableProjectProjectIdUsersUserIdPutRequest struct {
	value *ProjectProjectIdUsersUserIdPutRequest
	isSet bool
}

func (v NullableProjectProjectIdUsersUserIdPutRequest) Get() *ProjectProjectIdUsersUserIdPutRequest {
	return v.value
}

func (v *NullableProjectProjectIdUsersUserIdPutRequest) Set(val *ProjectProjectIdUsersUserIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectProjectIdUsersUserIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectProjectIdUsersUserIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectProjectIdUsersUserIdPutRequest(val *ProjectProjectIdUsersUserIdPutRequest) *NullableProjectProjectIdUsersUserIdPutRequest {
	return &NullableProjectProjectIdUsersUserIdPutRequest{value: val, isSet: true}
}

func (v NullableProjectProjectIdUsersUserIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectProjectIdUsersUserIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


