/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the UsersUserIdPasswordPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersUserIdPasswordPostRequest{}

// UsersUserIdPasswordPostRequest struct for UsersUserIdPasswordPostRequest
type UsersUserIdPasswordPostRequest struct {
	Password *string `json:"password,omitempty"`
}

// NewUsersUserIdPasswordPostRequest instantiates a new UsersUserIdPasswordPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersUserIdPasswordPostRequest() *UsersUserIdPasswordPostRequest {
	this := UsersUserIdPasswordPostRequest{}
	return &this
}

// NewUsersUserIdPasswordPostRequestWithDefaults instantiates a new UsersUserIdPasswordPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersUserIdPasswordPostRequestWithDefaults() *UsersUserIdPasswordPostRequest {
	this := UsersUserIdPasswordPostRequest{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *UsersUserIdPasswordPostRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserIdPasswordPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UsersUserIdPasswordPostRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *UsersUserIdPasswordPostRequest) SetPassword(v string) {
	o.Password = &v
}

func (o UsersUserIdPasswordPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersUserIdPasswordPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableUsersUserIdPasswordPostRequest struct {
	value *UsersUserIdPasswordPostRequest
	isSet bool
}

func (v NullableUsersUserIdPasswordPostRequest) Get() *UsersUserIdPasswordPostRequest {
	return v.value
}

func (v *NullableUsersUserIdPasswordPostRequest) Set(val *UsersUserIdPasswordPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersUserIdPasswordPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersUserIdPasswordPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersUserIdPasswordPostRequest(val *UsersUserIdPasswordPostRequest) *NullableUsersUserIdPasswordPostRequest {
	return &NullableUsersUserIdPasswordPostRequest{value: val, isSet: true}
}

func (v NullableUsersUserIdPasswordPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersUserIdPasswordPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


