/*
Semaphore API

Semaphore API provides endpoints for managing and interacting with the Semaphore UI. This documentation outlines the available operations and data models. 

API version: 2.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package semaphore

import (
	"encoding/json"
)

// checks if the IntegrationExtractValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationExtractValue{}

// IntegrationExtractValue struct for IntegrationExtractValue
type IntegrationExtractValue struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	ValueSource *string `json:"value_source,omitempty"`
	BodyDataType *string `json:"body_data_type,omitempty"`
	Key *string `json:"key,omitempty"`
	Variable *string `json:"variable,omitempty"`
	IntegrationId *int32 `json:"integration_id,omitempty"`
}

// NewIntegrationExtractValue instantiates a new IntegrationExtractValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationExtractValue() *IntegrationExtractValue {
	this := IntegrationExtractValue{}
	return &this
}

// NewIntegrationExtractValueWithDefaults instantiates a new IntegrationExtractValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationExtractValueWithDefaults() *IntegrationExtractValue {
	this := IntegrationExtractValue{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IntegrationExtractValue) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IntegrationExtractValue) SetName(v string) {
	o.Name = &v
}

// GetValueSource returns the ValueSource field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetValueSource() string {
	if o == nil || IsNil(o.ValueSource) {
		var ret string
		return ret
	}
	return *o.ValueSource
}

// GetValueSourceOk returns a tuple with the ValueSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetValueSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ValueSource) {
		return nil, false
	}
	return o.ValueSource, true
}

// HasValueSource returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasValueSource() bool {
	if o != nil && !IsNil(o.ValueSource) {
		return true
	}

	return false
}

// SetValueSource gets a reference to the given string and assigns it to the ValueSource field.
func (o *IntegrationExtractValue) SetValueSource(v string) {
	o.ValueSource = &v
}

// GetBodyDataType returns the BodyDataType field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetBodyDataType() string {
	if o == nil || IsNil(o.BodyDataType) {
		var ret string
		return ret
	}
	return *o.BodyDataType
}

// GetBodyDataTypeOk returns a tuple with the BodyDataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetBodyDataTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BodyDataType) {
		return nil, false
	}
	return o.BodyDataType, true
}

// HasBodyDataType returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasBodyDataType() bool {
	if o != nil && !IsNil(o.BodyDataType) {
		return true
	}

	return false
}

// SetBodyDataType gets a reference to the given string and assigns it to the BodyDataType field.
func (o *IntegrationExtractValue) SetBodyDataType(v string) {
	o.BodyDataType = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *IntegrationExtractValue) SetKey(v string) {
	o.Key = &v
}

// GetVariable returns the Variable field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetVariable() string {
	if o == nil || IsNil(o.Variable) {
		var ret string
		return ret
	}
	return *o.Variable
}

// GetVariableOk returns a tuple with the Variable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetVariableOk() (*string, bool) {
	if o == nil || IsNil(o.Variable) {
		return nil, false
	}
	return o.Variable, true
}

// HasVariable returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasVariable() bool {
	if o != nil && !IsNil(o.Variable) {
		return true
	}

	return false
}

// SetVariable gets a reference to the given string and assigns it to the Variable field.
func (o *IntegrationExtractValue) SetVariable(v string) {
	o.Variable = &v
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *IntegrationExtractValue) GetIntegrationId() int32 {
	if o == nil || IsNil(o.IntegrationId) {
		var ret int32
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationExtractValue) GetIntegrationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.IntegrationId) {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *IntegrationExtractValue) HasIntegrationId() bool {
	if o != nil && !IsNil(o.IntegrationId) {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given int32 and assigns it to the IntegrationId field.
func (o *IntegrationExtractValue) SetIntegrationId(v int32) {
	o.IntegrationId = &v
}

func (o IntegrationExtractValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationExtractValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ValueSource) {
		toSerialize["value_source"] = o.ValueSource
	}
	if !IsNil(o.BodyDataType) {
		toSerialize["body_data_type"] = o.BodyDataType
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Variable) {
		toSerialize["variable"] = o.Variable
	}
	if !IsNil(o.IntegrationId) {
		toSerialize["integration_id"] = o.IntegrationId
	}
	return toSerialize, nil
}

type NullableIntegrationExtractValue struct {
	value *IntegrationExtractValue
	isSet bool
}

func (v NullableIntegrationExtractValue) Get() *IntegrationExtractValue {
	return v.value
}

func (v *NullableIntegrationExtractValue) Set(val *IntegrationExtractValue) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationExtractValue) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationExtractValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationExtractValue(val *IntegrationExtractValue) *NullableIntegrationExtractValue {
	return &NullableIntegrationExtractValue{value: val, isSet: true}
}

func (v NullableIntegrationExtractValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationExtractValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


